const FEATURES = [
    {
        icon: (
            <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                />
            </svg>
        ),
        title: '20 latest reports',
        desc: 'Pulls the 20 most recent FDA adverse event reports for any drug.',
    },
    {
        icon: (
            <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"
                />
            </svg>
        ),
        title: 'Reaction tags',
        desc: 'Adverse reactions extracted and tagged by MedDRA preferred term.',
    },
    {
        icon: (
            <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                />
            </svg>
        ),
        title: 'Groq AI summary',
        desc: 'Plain-English clinical analysis generated by Groq model.',
    },
    {
        icon: (
            <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                />
            </svg>
        ),
        title: 'Patient demographics',
        desc: 'Age, sex, and outcome data surfaced for each reported event.',
    },
];

export default function EmptyState() {
    return (
        <div className="py-12 animate-fade-in">
            {/* Feature grid */}
            <div className="max-w-3xl mx-auto">
                <p className="text-center text-text-tertiary text-xs uppercase tracking-widest font-medium mb-8">
                    What you get
                </p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {FEATURES.map((f, i) => (
                        <div
                            key={i}
                            className="card p-5 flex items-start gap-4"
                            style={{ animationDelay: `${i * 80}ms` }}
                        >
                            <div className="w-9 h-9 rounded-lg bg-surface-3 flex items-center justify-center flex-shrink-0 text-text-secondary">
                                {f.icon}
                            </div>
                            <div>
                                <p className="text-sm font-medium text-text-primary mb-0.5">
                                    {f.title}
                                </p>
                                <p className="text-xs text-text-secondary leading-relaxed">
                                    {f.desc}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Disclaimer */}
                <div className="mt-8 p-4 rounded-xl bg-surface-2/50 border border-border-subtle text-center">
                    <p className="text-text-tertiary text-xs leading-relaxed">
                        RxSignal uses publicly available data from the FDA
                        Adverse Event Reporting System (FAERS) via the openFDA
                        API. Reports are submitted voluntarily and may not
                        represent all adverse events. This tool is for
                        informational purposes only — not a substitute for
                        professional medical advice.
                    </p>
                </div>
            </div>
        </div>
    );
}
